//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 01:52:27 PM MSK 
//


package by.bsu.web.sardyko.models.hour;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the by.bsu.web.sardyko.models.hour package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GetOpenHoursRequest_QNAME = new QName("http://sardyko.web.bsu.by/models/hour", "getOpenHoursRequest");
    private final static QName _IsOpenAtTheMomentRequest_QNAME = new QName("http://sardyko.web.bsu.by/models/hour", "isOpenAtTheMomentRequest");
    private final static QName _GetMinutesUntilCloseRequest_QNAME = new QName("http://sardyko.web.bsu.by/models/hour", "getMinutesUntilCloseRequest");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: by.bsu.web.sardyko.models.hour
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetMinutesUntilCloseResponse }
     * 
     */
    public GetMinutesUntilCloseResponse createGetMinutesUntilCloseResponse() {
        return new GetMinutesUntilCloseResponse();
    }

    /**
     * Create an instance of {@link IsOpenResponse }
     * 
     */
    public IsOpenResponse createIsOpenResponse() {
        return new IsOpenResponse();
    }

    /**
     * Create an instance of {@link GetOpenHoursResponse }
     * 
     */
    public GetOpenHoursResponse createGetOpenHoursResponse() {
        return new GetOpenHoursResponse();
    }

    /**
     * Create an instance of {@link HourList }
     * 
     */
    public HourList createHourList() {
        return new HourList();
    }

    /**
     * Create an instance of {@link GetOpenHoursForSpecificDayResponse }
     * 
     */
    public GetOpenHoursForSpecificDayResponse createGetOpenHoursForSpecificDayResponse() {
        return new GetOpenHoursForSpecificDayResponse();
    }

    /**
     * Create an instance of {@link Hour }
     * 
     */
    public Hour createHour() {
        return new Hour();
    }

    /**
     * Create an instance of {@link GetOpenHourForSpecificDayRequest }
     * 
     */
    public GetOpenHourForSpecificDayRequest createGetOpenHourForSpecificDayRequest() {
        return new GetOpenHourForSpecificDayRequest();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sardyko.web.bsu.by/models/hour", name = "getOpenHoursRequest")
    public JAXBElement<Object> createGetOpenHoursRequest(Object value) {
        return new JAXBElement<Object>(_GetOpenHoursRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sardyko.web.bsu.by/models/hour", name = "isOpenAtTheMomentRequest")
    public JAXBElement<Object> createIsOpenAtTheMomentRequest(Object value) {
        return new JAXBElement<Object>(_IsOpenAtTheMomentRequest_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://sardyko.web.bsu.by/models/hour", name = "getMinutesUntilCloseRequest")
    public JAXBElement<Object> createGetMinutesUntilCloseRequest(Object value) {
        return new JAXBElement<Object>(_GetMinutesUntilCloseRequest_QNAME, Object.class, null, value);
    }

}
