//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.28 at 01:27:29 PM MSK 
//


package by.bsu.web.sardyko.models.book;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="hourList" type="{http://sardyko.web.bsu.by/models/book}hourList"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "hourList"
})
@XmlRootElement(name = "getOpenHoursResponse")
public class GetOpenHoursResponse {

    @XmlElement(required = true)
    protected HourList hourList;

    /**
     * Gets the value of the hourList property.
     * 
     * @return
     *     possible object is
     *     {@link HourList }
     *     
     */
    public HourList getHourList() {
        return hourList;
    }

    /**
     * Sets the value of the hourList property.
     * 
     * @param value
     *     allowed object is
     *     {@link HourList }
     *     
     */
    public void setHourList(HourList value) {
        this.hourList = value;
    }

}
