
package by.bsu.client.remote;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "ReaderServiceDefaultService", targetNamespace = "http://services.server.bsu.by/", wsdlLocation = "http://localhost:8081/readerservice?wsdl")
public class ReaderServiceDefaultService
    extends Service
{

    private final static URL READERSERVICEDEFAULTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(by.bsu.client.remote.ReaderServiceDefaultService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = by.bsu.client.remote.ReaderServiceDefaultService.class.getResource(".");
            url = new URL(baseUrl, "http://localhost:8081/readerservice?wsdl");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:8081/readerservice?wsdl', retrying as a local file");
            logger.warning(e.getMessage());
        }
        READERSERVICEDEFAULTSERVICE_WSDL_LOCATION = url;
    }

    public ReaderServiceDefaultService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ReaderServiceDefaultService() {
        super(READERSERVICEDEFAULTSERVICE_WSDL_LOCATION, new QName("http://services.server.bsu.by/", "ReaderServiceDefaultService"));
    }

    /**
     * 
     * @return
     *     returns ReaderServiceDefault
     */
    @WebEndpoint(name = "ReaderServiceDefaultPort")
    public ReaderServiceDefault getReaderServiceDefaultPort() {
        return super.getPort(new QName("http://services.server.bsu.by/", "ReaderServiceDefaultPort"), ReaderServiceDefault.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ReaderServiceDefault
     */
    @WebEndpoint(name = "ReaderServiceDefaultPort")
    public ReaderServiceDefault getReaderServiceDefaultPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.server.bsu.by/", "ReaderServiceDefaultPort"), ReaderServiceDefault.class, features);
    }

}
