
package by.bsu.client.remote;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.7-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "ReaderServiceDefault", targetNamespace = "http://services.server.bsu.by/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ReaderServiceDefault {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns by.bsu.client.remote.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "takeBook", targetNamespace = "http://services.server.bsu.by/", className = "by.bsu.client.remote.TakeBook")
    @ResponseWrapper(localName = "takeBookResponse", targetNamespace = "http://services.server.bsu.by/", className = "by.bsu.client.remote.TakeBookResponse")
    public Book takeBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Reader arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Book arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "reportLostBook", targetNamespace = "http://services.server.bsu.by/", className = "by.bsu.client.remote.ReportLostBook")
    @ResponseWrapper(localName = "reportLostBookResponse", targetNamespace = "http://services.server.bsu.by/", className = "by.bsu.client.remote.ReportLostBookResponse")
    public void reportLostBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "returnBook", targetNamespace = "http://services.server.bsu.by/", className = "by.bsu.client.remote.ReturnBook")
    @ResponseWrapper(localName = "returnBookResponse", targetNamespace = "http://services.server.bsu.by/", className = "by.bsu.client.remote.ReturnBookResponse")
    public void returnBook(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "registerNewReader", targetNamespace = "http://services.server.bsu.by/", className = "by.bsu.client.remote.RegisterNewReader")
    @ResponseWrapper(localName = "registerNewReaderResponse", targetNamespace = "http://services.server.bsu.by/", className = "by.bsu.client.remote.RegisterNewReaderResponse")
    public void registerNewReader(
        @WebParam(name = "arg0", targetNamespace = "")
        Reader arg0);

}
